SELECT 
    cs.customer_segment,
    om.order_month,
    SUM(s.price) AS total_sales
FROM 
    vw_sales s
JOIN 
    vw_customer_segmentation cs ON s.customer_id = cs.customer_id
JOIN 
    vw_order_monthly om ON s.order_id = om.order_id
GROUP BY 
    cs.customer_segment, om.order_month;

-- What is the total profit generated by each region, 
-- and how does it correlate with the total number of returns from each region?

SELECT 
    c.customer_state AS region,
    SUM(s.profit) AS total_profit,
    COUNT(CASE WHEN r.is_returned = 1 THEN 1 END) AS total_returns
FROM 
    vw_sales s
JOIN 
    vw_returns r ON s.order_id = r.order_id
JOIN 
    olist_customers_dataset c ON s.customer_id = c.customer_id
GROUP BY 
    c.customer_state
ORDER BY 
    total_profit DESC;

--Which customers have the highest average sales per order, 
--and what is their return rate?
SELECT 
    --SUM(s.profit) AS total_profit,
	c.customer_id,
	sum(s.price) as total_sale,
    COUNT(CASE WHEN r.is_returned = 1 THEN 1 END) AS total_returns
FROM 
    vw_sales s
JOIN 
    vw_returns r ON s.order_id = r.order_id
JOIN 
    olist_customers_dataset c ON s.customer_id = c.customer_id
GROUP BY 
    c.customer_id
ORDER BY 
    total_sale DESC;

--What is the trend of monthly sales over the past three years, 
--segmented by region and customer segment?

SELECT 
    --SUM(s.profit) AS total_profit,
	cs.customer_segment,
	om.order_month, 
	om.order_year,
	sum(s.price) as total_sale
    --(CASE WHEN r.is_returned = 1 THEN 1 END) AS total_returns
FROM 
    vw_sales s
JOIN 
    vw_order_monthly om ON s.order_id = om.order_id
JOIN 
    vw_customer_segmentation cs ON s.customer_id = cs.customer_id
GROUP BY 
	om.order_year,
    om.order_month, 
	cs.customer_state,cs.customer_segment
order BY 
	om.order_year,
    om.order_month, 
	cs.customer_state,cs.customer_segment;

--Identify the top 10 products by sales in each region and determine
--their profit margins.

WITH regional_product_sales AS (
    SELECT 
        c.customer_state AS region,
        s.product_category_name,
        SUM(CASE WHEN r.is_returned = 0 THEN s.price END) AS total_sales,
        SUM(CASE WHEN r.is_returned = 0 THEN s.profit END) AS total_profit,
        -- Avoid divide-by-zero
        CASE 
            WHEN SUM(CASE WHEN r.is_returned = 0 THEN s.price END) = 0 THEN 0
            ELSE 
                SUM(CASE WHEN r.is_returned = 0 THEN s.profit END) * 1.0 / 
                SUM(CASE WHEN r.is_returned = 0 THEN s.price END)
        END AS profit_margin
    FROM 
        vw_sales s
    JOIN 
        vw_returns r ON s.order_id = r.order_id
    JOIN 
        olist_customers_dataset c ON s.customer_id = c.customer_id
    GROUP BY 
        c.customer_state, s.product_category_name
),
ranked_products AS (
    SELECT 
        *,
        ROW_NUMBER() OVER (
            PARTITION BY region 
            ORDER BY total_sales DESC
        ) AS product_rank
    FROM 
        regional_product_sales
)
SELECT 
    region,
    product_category_name,
    total_sales,
    total_profit,
    CAST(profit_margin * 100 AS DECIMAL(5,2)) AS profit_margin_percent
FROM 
    ranked_products
WHERE 
    product_rank <= 10
ORDER BY 
    region, total_sales DESC;


--Total Returns by Region and List of Customers Who Returned Orders

select cs.customer_state as region, count(r.customer_id) as total_returns from 
vw_returns r join vw_customer_segmentation cs on 
r.customer_id = cs.customer_id
where r.is_returned = 1
group by cs.customer_state
order by total_returns desc;

--How does the average discount given affect the total 
--sales and profit in each product category?
-- not applicable

--Which city has the highest return rate, 
--and what are the common products returned from that city?
select cs.customer_city as city, count(r.is_returned) as total_returns from 
vw_returns r join vw_customer_segmentation cs on 
r.customer_id = cs.customer_id
where r.is_returned = 1
group by cs.customer_city
order by total_returns desc;


